name: C/C++ CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : checkout repo
      uses: actions/checkout@v4
    - name : create output directory
      run : mkdir ./bin
    - name : change directory
      run : cd ./src
    - name: make
      run: make build
